on:
  push:
    tags:
      - '*'                                                 # (1)

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Markdown to PDF and HTML                      # (3)
        uses: BaileyJM02/markdown-to-pdf@v1.2.0
        with:
          input_dir: .
          output_dir: .
      - name: Rename pdf
        run: cp ./resume.pdf ./mazdak_nasab_resume.pdf
      - name: Create Release                                # (4)
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset                          # (5)
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mazdak_nasab_resume.pdf
          asset_name: mazdak_nasab_resume.pdf
          asset_content_type: application/pdf
